### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by mikkelmilo**
Had accidentally left a sentence from my fork in the readme.

### CODE REVIEW

**Comment by annenkov** [comment]
Since we need to write more detailed documentation for the artifact, maybe it's worth adding more details? Like description of which contracts where tested. Maybe we should create a separate readme in the `tests` folder?

**Comment by jakobbotsch** [comment]
Shouldn't we have a separate readme for the reviewers of the artifact (eg. pointing out what work from the current submission is where).

**Comment by annenkov** [comment]
> Shouldn't we have a separate readme for the reviewers of the artifact (eg. pointing out what work from the current submission is where)?
Yes, we should :) I thought we first do a more detailed description of all new stuff and after that create a branch where we add more guides for the reviewers.

**Comment by mikkelmilo** [comment]
> Since we need to write more detailed documentation for the artifact, maybe it's worth adding more details? Like description of which contracts where tested. Maybe we should create a separate readme in the `tests` folder?

there is a readme in the execution folder with a bit more detail about the testing, but I can expand on it. 

I think a description of tested contracts is sort of redundant, since in the tests/ folder there are folders for each tested contract (e.g. CongressTests/, EIP20Tests/, EscrowTests/, etc.). Shouldn't that be sufficient?

**Comment by mikkelmilo** [comment]
I've added some more details in the readme of the execution folder. What do you think?

**Comment by annenkov** [comment]
I agree the folder names are good enough to understand what is in them.
Your last update looks good to me.

**Pull request merged**
