### PR TITLE
Add a plugin to derive record setters using MetaCoq

### PR DESCRIPTION
**Pull request by jakobbotsch**
This replaces the coq-record-update plugin based on Ltac that we used to
define nice record update syntax with a similarly one (on the surface)
that uses MetaCoq to define setters. The benefits are that we can
produce better terms and that we no longer have to list each member of
records when deriving. The downside is that it does not support parameterised
records (but this can be worked around using sections).

### CODE REVIEW

**Comment by spitters** [comment]
Would it be worth moving this to a more central place?

**Comment by jakobbotsch** [comment]
Probably yes, but after this I found https://github.com/bedrocksystems/coq-lens which subsumes our stuff by a fair bit.  Ours is more guided to produce simple terms that extracts nicely, though...

**Comment by spitters** [comment]
Yes, I saw that before too. Russell was always very excited about lenses.

Do you see a way to integrate parts of our work with that? If there's no obvious way, we can just notify them about our work.

**Comment by annenkov** [comment]
I think lenses is a programming pattern, programming with nested records and stuff (they generalise, of course, to many different things, including dynamical systems). If we want to use this pattern, it's fine to try integrating. Otherwise, we can just use projections. Depends on how much abstraction overhead lenses bring.

**Comment by jakobbotsch** [comment]
This was the result of a few hours of work, I would want to polish it a bit more before I would suggest anyone else to use it or integrate it. In particular I would want to be able to adjust unfolding behavior through MetaCoq (i.e. give access to the `Argument` vernacular), support parameterized records and support primitive projections. But this would take more time :)

I'm not that familiar with lenses but it seems like coq-lens supplies at least the stuff we want (simple setters).

**Comment by annenkov** [comment]
>I would want to polish it a bit more before I would suggest anyone else to use it or integrate it

Ah, ok, I thought Bas asked if we can integrate lenses to ConCert. Your setter generation might produce less overhead, which is important for our purposes.

**Pull request merged**
